return {
  {
    'catppuccin/nvim',
    name = 'catppuccin',
    priority = 1000,
    opts = {
      integrations = {
        bufferline = true,
      },
    },
  },

  { 'folke/tokyonight.nvim', priority = 1000 },
  { 'navarasu/onedark.nvim', priority = 1000 },
  { 'tiagovla/tokyodark.nvim', priority = 1000 },
  { 'EdenEast/nightfox.nvim', priority = 1000 },
  { 'shaunsingh/nord.nvim', priority = 1000 },
  { 'rose-pine/neovim', name = 'rose-pine', priority = 1000 },
  { 'rebelot/kanagawa.nvim', priority = 1000 },
  { 'marko-cerovac/material.nvim', priority = 1000 },
  { 'nyoom-engineering/oxocarbon.nvim', priority = 1000 },
  { 'projekt0n/github-nvim-theme', priority = 1000 },
  { 'sainnhe/everforest', priority = 1000 },
  { 'sainnhe/gruvbox-material', priority = 1000 },
  { 'ellisonleao/gruvbox.nvim', priority = 1000 },
  { 'luisiacc/gruvbox-baby', branch = 'main', priority = 1000 },
  { 'oxfist/night-owl.nvim', priority = 1000 },
  {
    'mcchrish/zenbones.nvim',
    dependencies = { 'rktjmp/lush.nvim' },
    priority = 1000,
  },
  { 'Yazeed1s/minimal.nvim', priority = 1000 },
  { 'Shatur/neovim-ayu', priority = 1000 },
  { 'olimorris/onedarkpro.nvim', priority = 1000 },
  { 'Mofiqul/vscode.nvim', priority = 1000 },
  { 'loctvl842/monokai-pro.nvim', priority = 1000 },
  { 'maxmx03/fluoromachine.nvim', priority = 1000 },
  { 'kaiuri/nvim-juliana', priority = 1000 },
  { 'ribru17/bamboo.nvim', priority = 1000 },
  { 'aktersnurra/no-clown-fiesta.nvim', priority = 1000 },
  { 'askfiy/visual_studio_code', priority = 1000 },
  { 'jacoborus/tender.vim', priority = 1000 },
}
